"""M1 initial schema

The whole CLAUDE.md section 7 schema in one revision.

Three hand edits on top of autogenerate, all of which autogenerate gets wrong:

1. `import pgvector` was missing. Autogenerate emits
   `pgvector.sqlalchemy.vector.VECTOR(dim=1536)` for the embedding column but
   never adds the import, so the revision raised NameError on run.
2. `CREATE EXTENSION IF NOT EXISTS vector` was added at the top of upgrade().
   Without it this revision only works on a database where
   docker/postgres-init.sql happened to run, which is to say on a container
   whose volume was fresh. Migrations have to stand on their own.
3. downgrade() drops the nine native enum types explicitly. Postgres creates
   an enum type as a side effect of CREATE TABLE but does not drop it on DROP
   TABLE, so without this a downgrade leaves the types orphaned and the next
   upgrade fails with "type already exists".

Revision ID: b270ce1b80cd
Revises:
Create Date: 2026-08-06 00:32:47.475494

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b270ce1b80cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Native Postgres enum types created implicitly by the CREATE TABLE statements
# below. Listed so downgrade() can drop them; see hand edit 3 above.
ENUM_TYPES = (
    "trip_status",
    "constraint_kind",
    "candidate_type",
    "badge_type",
    "vote_signal",
    "itinerary_status",
    "itinerary_created_by",
    "replan_trigger",
    "replan_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector backs candidate_place.embedding (dedup similarity, section 8.4).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_scenario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('fixture_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('disruption_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_scenario')),
    sa.UniqueConstraint('name', name=op.f('uq_eval_scenario_name'))
    )
    op.create_table('trip',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('setup', 'swiping', 'shortlisting', 'scheduling', 'active', 'disrupted', name='trip_status'), server_default='setup', nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip'))
    )
    op.create_table('agent_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('step_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('token_cost', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_agent_run_trip_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_run'))
    )
    op.create_index(op.f('ix_agent_run_trace_id'), 'agent_run', ['trace_id'], unique=False)
    op.create_index(op.f('ix_agent_run_trip_id'), 'agent_run', ['trip_id'], unique=False)
    op.create_table('candidate_place',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('attraction', 'food', 'lodging', name='candidate_type'), nullable=False),
    sa.Column('name_canonical', sa.Text(), nullable=False),
    sa.Column('name_original_lang', sa.Text(), nullable=True),
    sa.Column('lat', sa.Double(), nullable=False),
    sa.Column('lng', sa.Double(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('hours_by_weekday', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('price_tier', sa.Integer(), server_default='2', nullable=False),
    sa.Column('duration_estimate_min', sa.Integer(), server_default='60', nullable=False),
    sa.Column('dietary_tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('weather_dependent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reservation_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fatigue_cost', sa.Integer(), server_default='2', nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('enrichment', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('trending_signals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_candidate_place_trip_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_place'))
    )
    op.create_index(op.f('ix_candidate_place_trip_id'), 'candidate_place', ['trip_id'], unique=False)
    op.create_index('ix_candidate_place_trip_id_type', 'candidate_place', ['trip_id', 'type'], unique=False)
    op.create_table('eval_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('scores_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['eval_scenario.id'], name=op.f('fk_eval_result_scenario_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_result'))
    )
    op.create_index('ix_eval_result_commit_sha_scenario_id', 'eval_result', ['commit_sha', 'scenario_id'], unique=False)
    op.create_index(op.f('ix_eval_result_scenario_id'), 'eval_result', ['scenario_id'], unique=False)
    op.create_table('itinerary_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'active', 'superseded', 'rejected', name='itinerary_status'), server_default='proposed', nullable=False),
    sa.Column('created_by', sa.Enum('agent', 'user', name='itinerary_created_by'), server_default='agent', nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('objective_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['itinerary_version.id'], name=op.f('fk_itinerary_version_parent_version_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_itinerary_version_trip_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_version')),
    sa.UniqueConstraint('trip_id', 'version_no', name='uq_itinerary_version_no_per_trip')
    )
    op.create_index(op.f('ix_itinerary_version_parent_version_id'), 'itinerary_version', ['parent_version_id'], unique=False)
    op.create_index(op.f('ix_itinerary_version_trip_id'), 'itinerary_version', ['trip_id'], unique=False)
    op.create_table('shortlist_state',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('selected_candidate_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('must_go_candidate_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('confirmed_by', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wishlist_excluded_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_shortlist_state_trip_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id', name=op.f('pk_shortlist_state'))
    )
    op.create_table('traveler',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('home_city', sa.Text(), nullable=True),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_traveler_trip_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traveler'))
    )
    op.create_index(op.f('ix_traveler_trip_id'), 'traveler', ['trip_id'], unique=False)
    op.create_table('candidate_badge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('traveler_id', sa.Uuid(), nullable=False),
    sa.Column('badge_type', sa.Enum('warning', 'confirm', 'neutral', name='badge_type'), nullable=False),
    sa.Column('badge_text', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_place.id'], name=op.f('fk_candidate_badge_candidate_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['traveler.id'], name=op.f('fk_candidate_badge_traveler_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_badge')),
    sa.UniqueConstraint('candidate_id', 'traveler_id', name='uq_candidate_badge_per_traveler')
    )
    op.create_index(op.f('ix_candidate_badge_candidate_id'), 'candidate_badge', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_badge_traveler_id'), 'candidate_badge', ['traveler_id'], unique=False)
    op.create_table('itinerary_node',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('fixed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('lock_reason', sa.Text(), nullable=True),
    sa.Column('transit_from_prev_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('transit_from_prev_mode', sa.Text(), nullable=True),
    sa.Column('notes_for_travelers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_place.id'], name=op.f('fk_itinerary_node_candidate_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['itinerary_version.id'], name=op.f('fk_itinerary_node_version_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_node'))
    )
    op.create_index(op.f('ix_itinerary_node_candidate_id'), 'itinerary_node', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_itinerary_node_version_id'), 'itinerary_node', ['version_id'], unique=False)
    op.create_index('ix_itinerary_node_version_id_day_start_time', 'itinerary_node', ['version_id', 'day', 'start_time'], unique=False)
    op.create_table('replan_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.Enum('reservation_cancelled', 'transit_delay', 'overslept', 'place_closed', 'weather', 'other', name='replan_trigger'), nullable=False),
    sa.Column('trigger_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('affected_node_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('trace_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('proposed_version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='replan_status'), server_default='pending', nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['traveler.id'], name=op.f('fk_replan_event_decided_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_version_id'], ['itinerary_version.id'], name=op.f('fk_replan_event_proposed_version_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_replan_event_trip_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replan_event'))
    )
    op.create_index(op.f('ix_replan_event_decided_by'), 'replan_event', ['decided_by'], unique=False)
    op.create_index(op.f('ix_replan_event_proposed_version_id'), 'replan_event', ['proposed_version_id'], unique=False)
    op.create_index(op.f('ix_replan_event_trip_id'), 'replan_event', ['trip_id'], unique=False)
    op.create_table('trip_constraint',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('traveler_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='1', nullable=False),
    sa.Column('kind', sa.Enum('hard', 'soft', name='constraint_kind'), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['traveler.id'], name=op.f('fk_trip_constraint_traveler_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_trip_constraint_trip_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_constraint'))
    )
    op.create_index(op.f('ix_trip_constraint_traveler_id'), 'trip_constraint', ['traveler_id'], unique=False)
    op.create_index(op.f('ix_trip_constraint_trip_id'), 'trip_constraint', ['trip_id'], unique=False)
    op.create_table('vote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('traveler_id', sa.Uuid(), nullable=False),
    sa.Column('signal', sa.Enum('like', 'dislike', 'like_with_note', 'must_have', name='vote_signal'), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('note_parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_place.id'], name=op.f('fk_vote_candidate_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['traveler.id'], name=op.f('fk_vote_traveler_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote')),
    sa.UniqueConstraint('candidate_id', 'traveler_id', name='uq_vote_per_traveler')
    )
    op.create_index(op.f('ix_vote_candidate_id'), 'vote', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_vote_traveler_id'), 'vote', ['traveler_id'], unique=False)
    op.create_table('wishlist_not_placed',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_place.id'], name=op.f('fk_wishlist_not_placed_candidate_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['itinerary_version.id'], name=op.f('fk_wishlist_not_placed_version_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'candidate_id', name=op.f('pk_wishlist_not_placed'))
    )
    op.create_index('ix_wishlist_not_placed_candidate_id', 'wishlist_not_placed', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wishlist_not_placed_candidate_id', table_name='wishlist_not_placed')
    op.drop_table('wishlist_not_placed')
    op.drop_index(op.f('ix_vote_traveler_id'), table_name='vote')
    op.drop_index(op.f('ix_vote_candidate_id'), table_name='vote')
    op.drop_table('vote')
    op.drop_index(op.f('ix_trip_constraint_trip_id'), table_name='trip_constraint')
    op.drop_index(op.f('ix_trip_constraint_traveler_id'), table_name='trip_constraint')
    op.drop_table('trip_constraint')
    op.drop_index(op.f('ix_replan_event_trip_id'), table_name='replan_event')
    op.drop_index(op.f('ix_replan_event_proposed_version_id'), table_name='replan_event')
    op.drop_index(op.f('ix_replan_event_decided_by'), table_name='replan_event')
    op.drop_table('replan_event')
    op.drop_index('ix_itinerary_node_version_id_day_start_time', table_name='itinerary_node')
    op.drop_index(op.f('ix_itinerary_node_version_id'), table_name='itinerary_node')
    op.drop_index(op.f('ix_itinerary_node_candidate_id'), table_name='itinerary_node')
    op.drop_table('itinerary_node')
    op.drop_index(op.f('ix_candidate_badge_traveler_id'), table_name='candidate_badge')
    op.drop_index(op.f('ix_candidate_badge_candidate_id'), table_name='candidate_badge')
    op.drop_table('candidate_badge')
    op.drop_index(op.f('ix_traveler_trip_id'), table_name='traveler')
    op.drop_table('traveler')
    op.drop_table('shortlist_state')
    op.drop_index(op.f('ix_itinerary_version_trip_id'), table_name='itinerary_version')
    op.drop_index(op.f('ix_itinerary_version_parent_version_id'), table_name='itinerary_version')
    op.drop_table('itinerary_version')
    op.drop_index(op.f('ix_eval_result_scenario_id'), table_name='eval_result')
    op.drop_index('ix_eval_result_commit_sha_scenario_id', table_name='eval_result')
    op.drop_table('eval_result')
    op.drop_index('ix_candidate_place_trip_id_type', table_name='candidate_place')
    op.drop_index(op.f('ix_candidate_place_trip_id'), table_name='candidate_place')
    op.drop_table('candidate_place')
    op.drop_index(op.f('ix_agent_run_trip_id'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_trace_id'), table_name='agent_run')
    op.drop_table('agent_run')
    op.drop_table('trip')
    op.drop_table('eval_scenario')
    # ### end Alembic commands ###
    # Hand edit: DROP TABLE does not drop the enum types it implicitly
    # created. Leaving them behind makes the next upgrade fail.
    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # The vector extension is deliberately NOT dropped. It may be shared with
    # other schemas in the same database, and dropping it would cascade.
